/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package libplctag.java;

import org.libplctag.Tag;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

public class TagTest {
	static final int TIMEOUT = 5000;
	
    @Test public void testTag() {
        // set the debug level.
        Tag.setDebugLevel(Tag.PLCTAG_DEBUG_DETAIL);
       
        Tag tag = new Tag("make=system&family=library&name=debug", TIMEOUT);
        assertEquals("Tag was not created correctly!", tag.status(), Tag.PLCTAG_STATUS_OK);
        
        // write the DEBUG_DETAIL log value.
        assertEquals("Unable to update debug tag!", tag.setInt32(0, Tag.PLCTAG_DEBUG_INFO), Tag.PLCTAG_STATUS_OK);
        
        // write the tag.
        assertEquals("Unable to write debug tag!", tag.write(TIMEOUT), Tag.PLCTAG_STATUS_OK);
        
        // attempt read the DEBUG log value.
        assertEquals("Debug value not set!", Tag.getLibraryAttribute("debug", -1), Tag.PLCTAG_DEBUG_INFO);
        
        tag.close();
    }
}
